const EXPRESSION_TYPE = Symbol("EXPRESSION_TYPE");

const NUMERIC_PRIMITIVE = 'NUMERIC_PRIMITIVE';
const BINARY_EXPRESSION = 'BINARY_EXPRESSION';

module.exports = { EXPRESSION_TYPE, NUMERIC_PRIMITIVE, BINARY_EXPRESSION }